name: flutter_hive
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  logger: ^1.1.0
  flutter_svg: ^0.22.0
  get_it: ^7.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_easyloading: ^3.0.3
  form_builder: ^1.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
